version: '3.4'

services:
  iotrestfullapi:
    image: ${DOCKER_REGISTRY-}iotrestfullapi
    build:
      context: .
      dockerfile: IotRestFullApi/Dockerfile
    environment:
      - DATABASE_HOST=Server=iotrestfullapisqlserver;
    depends_on:
        - iotrestfullapisqlserver
    ports:
        - "6080:80"
        - "6433:433"
  iotrestfullapisqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Iot_Rest_Sql_Dev"
      MSSQL_PID: Express
    ports:
        - "1433:1433"