version: '3.6'

services:
  iotrestfullapi:
    image: ${DOCKER_REGISTRY-}iotrestfullapi
    build:
      context: .
      dockerfile: IotRestFullApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_HOST=Server=iotrestfullapisqlserver;
    depends_on:
      - iotrestfullapisqlserver
      - iotrestapiseq
    ports:
      - "6080:80"
      - "6090:5000"
    volumes:
      - ~/.aspnet/https:/https:ro
  iotrestfullapisqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Iot_Rest_Sql_Dev"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  iotrestapiseq:
    image: datalust/seq:latest
    ports:
      - "6100:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"