// <auto-generated />
using System;
using IotRestFullApi.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IotRestFullApi.Migrations
{
    [DbContext(typeof(IotContext))]
    [Migration("20210803171205_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IotRestFullApi.Entities.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUid");

                    b.ToTable("Command");
                });

            modelBuilder.Entity("IotRestFullApi.Entities.Device", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("IotRestFullApi.Entities.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceUid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUid");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("IotRestFullApi.Entities.Command", b =>
                {
                    b.HasOne("IotRestFullApi.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceUid");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IotRestFullApi.Entities.Stats", b =>
                {
                    b.HasOne("IotRestFullApi.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceUid");

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
